CROP_INFO = {
    'rice': {'name': 'Rice', 'icon': '🌾', 'season': 'Kharif (June-Nov)', 'water': 'High (Standing Water)', 'soil': 'Clay/Clayey Loam', 'temp': '20-35°C'},
    'wheat': {'name': 'Wheat', 'icon': '🌾', 'season': 'Rabi (Nov-April)', 'water': 'Medium (4-6 Irrigations)', 'soil': 'Silty Loam', 'temp': '15-25°C'},
    'maize': {'name': 'Maize', 'icon': '🌽', 'season': 'Kharif/Rabi', 'water': 'Medium', 'soil': 'Well-drained Loam', 'temp': '22-30°C'},
    'cotton': {'name': 'Cotton', 'icon': '🌿', 'season': 'Kharif (May-Oct)', 'water': 'Medium', 'soil': 'Deep Black Soil', 'temp': '25-35°C'},
    'banana': {'name': 'Banana', 'icon': '🍌', 'season': 'Year-round', 'water': 'Very High', 'soil': 'Rich Volcanic/Alluvial', 'temp': '20-30°C'},
    'mango': {'name': 'Mango', 'icon': '🥭', 'season': 'Perennial', 'water': 'Low/Medium', 'soil': 'Deep Loamy', 'temp': '24-30°C'},
    'grapes': {'name': 'Grapes', 'icon': '🍇', 'season': 'Dec-May', 'water': 'Medium', 'soil': 'Sandy Loam', 'temp': '15-35°C'},
    'watermelon': {'name': 'Watermelon', 'icon': '🍉', 'season': 'Summer (Feb-June)', 'water': 'Medium', 'soil': 'Sandy to Sandy Loam', 'temp': '24-30°C'},
    'muskmelon': {'name': 'Muskmelon', 'icon': '🍈', 'season': 'Summer', 'water': 'Medium', 'soil': 'Sandy Loam', 'temp': '24-30°C'},
    'apple': {'name': 'Apple', 'icon': '🍎', 'season': 'Rabi (Oct-Feb)', 'water': 'Medium', 'soil': 'Well-drained Loam', 'temp': '10-25°C'},
    'orange': {'name': 'Orange', 'icon': '🍊', 'season': 'Year-round', 'water': 'Medium', 'soil': 'Light Loamy', 'temp': '13-37°C'},
    'papaya': {'name': 'Papaya', 'icon': '🥭', 'season': 'Year-round', 'water': 'Medium', 'soil': 'Well-drained Rich', 'temp': '25-30°C'},
    'coconut': {'name': 'Coconut', 'icon': '🥥', 'season': 'Perennial', 'water': 'High', 'soil': 'Sandy/Alluvial', 'temp': '20-30°C'},
    'pomegranate': {'name': 'Pomegranate', 'icon': '🍎', 'season': 'Year-round', 'water': 'Low', 'soil': 'Diverse (Well-drained)', 'temp': '25-35°C'},
    'coffee': {'name': 'Coffee', 'icon': '☕', 'season': 'Perennial', 'water': 'High', 'soil': 'Deep Rich Loam', 'temp': '15-28°C'},
    'tea': {'name': 'Tea', 'icon': '🍃', 'season': 'Perennial', 'water': 'High', 'soil': 'Acidic Forest Soil', 'temp': '13-32°C'},
    'tobacco': {'name': 'Tobacco', 'icon': '🍂', 'season': 'Rabi', 'water': 'Medium', 'soil': 'Sandy Loam', 'temp': '20-30°C'},
    'mungbean': {'name': 'Mungbean', 'icon': '🌱', 'season': 'Kharif/Summer', 'water': 'Low', 'soil': 'Loamy to Sandy Loam', 'temp': '25-35°C'},
    'blackgram': {'name': 'Blackgram', 'icon': '🌱', 'season': 'Kharif', 'water': 'Low', 'soil': 'Heavy Clay', 'temp': '25-35°C'},
    'lentil': {'name': 'Lentil', 'icon': '🍛', 'season': 'Rabi', 'water': 'Low', 'soil': 'Diverse Loams', 'temp': '18-30°C'},
    'pigeonpeas': {'name': 'Pigeonpeas', 'icon': '🌱', 'season': 'Kharif', 'water': 'Low', 'soil': 'Well-drained Loam', 'temp': '20-30°C'},
    'mothbeans': {'name': 'Mothbeans', 'icon': '🌱', 'season': 'Kharif/Summer', 'water': 'Very Low', 'soil': 'Sandy', 'temp': '25-35°C'},
    'chickpea': {'name': 'Chickpea', 'icon': '🥣', 'season': 'Rabi', 'water': 'Low', 'soil': 'Diverse Loams', 'temp': '15-25°C'},
    'kidneybeans': {'name': 'Kidney Beans', 'icon': '🧶', 'season': 'Rabi/Kharif', 'water': 'Medium', 'soil': 'Deep Silty Loam', 'temp': '15-25°C'},
    'jute': {'name': 'Jute', 'icon': '🧵', 'season': 'Kharif', 'water': 'High', 'soil': 'New Alluvial', 'temp': '24-34°C'},
}

MARKET_PRICES = [
    {'commodity': 'Basmati Rice', 'market': 'Azadpur', 'state': 'Delhi', 'min': 3500, 'max': 4500, 'modal': 4000, 'trend': 'up', 'change_percent': 5.2},
    {'commodity': 'Wheat', 'market': 'Khanna', 'state': 'Punjab', 'min': 2400, 'max': 2700, 'modal': 2550, 'trend': 'stable', 'change_percent': 0.1},
    {'commodity': 'Maize', 'market': 'Gultekdi', 'state': 'MS', 'min': 1800, 'max': 2100, 'modal': 1950, 'trend': 'down', 'change_percent': 2.5},
    {'commodity': 'Cotton', 'market': 'APMC Gujarat', 'state': 'GJ', 'min': 5800, 'max': 6400, 'modal': 6100, 'trend': 'up', 'change_percent': 3.8},
    {'commodity': 'Soybean', 'market': 'Indore', 'state': 'MP', 'min': 4200, 'max': 4800, 'modal': 4500, 'trend': 'up', 'change_percent': 1.5},
    {'commodity': 'Tomato', 'market': 'Kolar', 'state': 'KA', 'min': 600, 'max': 1200, 'modal': 900, 'trend': 'down', 'change_percent': 12.0},
]
